site_name: MicroData

repo_name: "2024.2-T03-MicroData"
repo_url: "https://github.com/mdsreq-fga-unb/2024.2-T03-MicroData"

theme:
  name: material
  palette:
    primary: red

nav:
  - Pagina Inicial: index.md
  - Cenário atual do cliente e do Negócio: cenario_cliente/cenario.md
  - Visão do Produto e Projeto:
    - Solução Proposta: visao_produto_projeto/visao_do_produto.md
    - Estratégias de Engenharia: estrategias_de_engenharia/estrategias.md
    - Engenharia de Requisitos: engenharia_requisitos/requisitos.md
    - Requisitos de Software: requisitos/requisitos.md
    - Backlog do Produto: backlog/backlog.md
    - Interação entre Equipe e Cliente: interacao_equipe_cliente/interacao.md
    - Cronograma e Entregas: cronograma_entregas/cronograma.md
  - Entregas: entregas/entregas.md
  - Lições Aprendidas: licoes_aprendidas/licoes.md


